micronaut:
  application:
    name: phonenumber
  server:
    port: 8080 # default: -1 (random port)
    cors:
    #enabled: true # default: false
  router:
    static-resources:
      # YAML file will be available at http://localhost:8080/swagger/greeter-microservice-0.1.0.yml
      # where "greeter-microservice-0.1.0" is derived from the Title and Version attributes of @OpenAPIDefinition
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
#  security:
#    # default: false
#    enabled: true
jackson:
  serialization:
    indentOutput: true

app:
  format:
    default-region: "DE"


